# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PW.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
gamedb=sqlite3.connect('GameData.db')
gamecur=gamedb.cursor()


class Ui_PerformanceWindow(object):

    def ScoreCalc(self):
        gamecur.execute("SELECT * FROM teams WHERE TeamName='"+self.TeamList.currentText()+"';")
        cat=gamecur.fetchall()
        Totalpoints=0
        for i in cat:
            points=0
            gamecur.execute("SELECT * FROM match WHERE Player='"+i[1]+"';")
            stat=gamecur.fetchall()
            for player in stat:
                runs=int(player[1])
                balls=int(player[2])
                four=int(player[3])
                six=int(player[4])
                wkts=int(player[8])
            if i[2]=="BAT" or i[2]=="AR":
                points=runs/2
                if runs>=50:
                    points=points+5
                if runs>=100:
                    points=points+10
                strike=(runs/balls)*100
                if 80<=strike<=100:
                    points = points+2
                if strike > 100:
                    points=points+4
                points=points+four+2*six
            if i[2]=="BOW" or i[2]=="AR" or i[2]=="WK":
                points=points+wkts*10
                overs=balls/6
                if wkts>=3:
                    points=points+5
                if wkts>=5:
                    points=points+10
                ecorate=runs/overs
                if 3.5<=ecorate<=4.5:
                    points=points+4
                if 2<=ecorate<=3.5:
                    points=points+7
                if ecorate<2:
                    points=points+10
            points=int(points)
            Totalpoints+=points
            self.PointsList.addItem(str(points))
        self.PointsD.setText(str(Totalpoints))
        self.StatusbarPW.setText("There's your Score!")
        gamecur.execute("INSERT INTO result VALUES(?,?,?)",(self.TeamList.currentText(),Totalpoints,self.MatchList.currentText()))
        gamedb.commit()
 
    def TeamFetch(self):
        self.PlayersList.clear()
        self.PointsList.clear()
        self.PointsD.setText("")
        gamecur.execute("SELECT Players from teams WHERE TeamName='"+self.TeamList.currentText()+"';")
        result=gamecur.fetchall()
        for each in result:
           self.PlayersList.addItem(each[0])
        self.StatusbarPW.setText("Now Click on Calculate to see how well your Team performed!")

    def setupUi(self, PerformanceWindow):
        PerformanceWindow.setObjectName("PerformanceWindow")
        PerformanceWindow.resize(316, 368)
        self.centralwidget = QtWidgets.QWidget(PerformanceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.TopL = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.TopL.setFont(font)
        self.TopL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TopL.setObjectName("TopL")
        self.gridLayout.addWidget(self.TopL, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ScoreButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ScoreButton.setFont(font)
        self.ScoreButton.setObjectName("ScoreButton")
        self.horizontalLayout_4.addWidget(self.ScoreButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 8, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PlayersList = QtWidgets.QListWidget(self.centralwidget)
        self.PlayersList.setObjectName("PlayersList")
        self.horizontalLayout_2.addWidget(self.PlayersList)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.PointsList = QtWidgets.QListWidget(self.centralwidget)
        self.PointsList.setObjectName("PointsList")
        self.horizontalLayout_2.addWidget(self.PointsList)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TeamList = QtWidgets.QComboBox(self.centralwidget)
        self.TeamList.setObjectName("TeamList")
        self.horizontalLayout.addWidget(self.TeamList)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.MatchList = QtWidgets.QComboBox(self.centralwidget)
        self.MatchList.setObjectName("MatchList")
        self.horizontalLayout.addWidget(self.MatchList)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.PlayersL = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PlayersL.setFont(font)
        self.PlayersL.setObjectName("PlayersL")
        self.horizontalLayout_3.addWidget(self.PlayersL)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.PointsL = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PointsL.setFont(font)
        self.PointsL.setObjectName("PointsL")
        self.horizontalLayout_3.addWidget(self.PointsL)
        self.PointsD = QtWidgets.QLineEdit(self.centralwidget)
        self.PointsD.setReadOnly(True)
        self.PointsD.setObjectName("PointsD")
        self.horizontalLayout_3.addWidget(self.PointsD)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.SelectTeamL = QtWidgets.QLabel(self.centralwidget)
        self.SelectTeamL.setObjectName("SelectTeamL")
        self.horizontalLayout_5.addWidget(self.SelectTeamL)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.SelectMatchL = QtWidgets.QLabel(self.centralwidget)
        self.SelectMatchL.setObjectName("SelectMatchL")
        self.horizontalLayout_5.addWidget(self.SelectMatchL)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.StatusbarPW = QtWidgets.QLabel(self.centralwidget)
        self.StatusbarPW.setText("Select a Team and Select a Match to Calculate Points")
        self.StatusbarPW.setObjectName("StatusbarPW")
        self.gridLayout.addWidget(self.StatusbarPW, 9, 0, 1, 1)
        PerformanceWindow.setCentralWidget(self.centralwidget)

        gamecur.execute("SELECT DISTINCT TeamName FROM teams")
        teams=gamecur.fetchall()
        for i in teams:
            self.TeamList.addItem(i[0])
        for i in range(10):
            self.MatchList.addItem("Match "+str(i+1))

        self.ScoreButton.clicked.connect(self.ScoreCalc)
        self.TeamList.activated.connect(self.TeamFetch)
        
        self.retranslateUi(PerformanceWindow)
        self.TeamList.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(PerformanceWindow)

    def retranslateUi(self, PerformanceWindow):
        _translate = QtCore.QCoreApplication.translate
        PerformanceWindow.setWindowTitle(_translate("PerformanceWindow", "Evaluate Performance"))
        self.TopL.setText(_translate("PerformanceWindow", "Evaluate the Performance of Fantasy Teams"))
        self.ScoreButton.setText(_translate("PerformanceWindow", "Calculate Score"))
        self.PlayersL.setText(_translate("PerformanceWindow", "Players"))
        self.PointsL.setText(_translate("PerformanceWindow", "Points"))
        self.SelectTeamL.setText(_translate("PerformanceWindow", "Select Team"))
        self.SelectMatchL.setText(_translate("PerformanceWindow", "Select Match"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PerformanceWindow = QtWidgets.QMainWindow()
    ui = Ui_PerformanceWindow()
    ui.setupUi(PerformanceWindow)
    PerformanceWindow.show()
    sys.exit(app.exec_())
